from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

MARKER_START = "<!-- vault-sync:start -->"
MARKER_END = "<!-- vault-sync:end -->"


@dataclass
class ParsedNote:
    frontmatter: dict = field(default_factory=dict)
    body: str = ""


def parse_note_text(text: str) -> ParsedNote:
    """Split `---`-delimited scalar frontmatter from the body.

    Only `key: value` pairs are recognized. Lines without `:` inside the
    frontmatter region are skipped silently.
    """
    if not text.startswith("---\n"):
        return ParsedNote(frontmatter={}, body=text)
    rest = text[len("---\n"):]
    end = rest.find("\n---\n")
    if end == -1:
        return ParsedNote(frontmatter={}, body=text)
    fm_block = rest[:end]
    body = rest[end + len("\n---\n"):]
    fm: dict = {}
    for line in fm_block.splitlines():
        if ":" not in line:
            continue
        k, _, v = line.partition(":")
        fm[k.strip()] = v.strip()
    return ParsedNote(frontmatter=fm, body=body)


def render_note(parsed: ParsedNote) -> str:
    if not parsed.frontmatter:
        return parsed.body
    lines = [f"{k}: {v}" for k, v in parsed.frontmatter.items()]
    return "---\n" + "\n".join(lines) + "\n---\n" + parsed.body


def update_frontmatter_fields(parsed: ParsedNote, **fields: str) -> ParsedNote:
    """Return a new ParsedNote with the given keys set/replaced.

    Order: existing keys keep their position; new keys are appended.
    """
    fm = dict(parsed.frontmatter)
    for k, v in fields.items():
        fm[k] = v
    return ParsedNote(frontmatter=fm, body=parsed.body)


def has_valid_markers(body: str) -> bool:
    starts = [i for i in range(len(body)) if body.startswith(MARKER_START, i)]
    ends = [i for i in range(len(body)) if body.startswith(MARKER_END, i)]
    if len(starts) != 1 or len(ends) != 1:
        return False
    return starts[0] < ends[0]


def resolve_note_path(vault_dir: Path, name: str) -> Path:
    """Folder-form preferred if `01_Projects/<name>/` exists; else file-form."""
    folder = vault_dir / "01_Projects" / name
    if folder.is_dir():
        return folder / f"{name}.md"
    return vault_dir / "01_Projects" / f"{name}.md"


def default_skeleton() -> str:
    """Initial body for a brand-new note: empty marker block, plus a Notes
    region the user can extend. Frontmatter is added by the caller.
    """
    return (
        f"\n{MARKER_START}\n"
        "## Project Snapshot\n"
        "*Auto-generated by project_sync. Do not edit between markers — "
        "changes will be overwritten on next sync.*\n"
        f"{MARKER_END}\n\n"
        "## Notes\n"
        "<!-- Free-form. project_sync never touches this region. -->\n"
    )


__all__ = [
    "MARKER_START",
    "MARKER_END",
    "ParsedNote",
    "parse_note_text",
    "render_note",
    "update_frontmatter_fields",
    "has_valid_markers",
    "resolve_note_path",
    "default_skeleton",
]
